server:
  port: 8080

grpc:
  server:
    port: 9090

spring:
  output:
    ansi:
      enabled: always

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers=localhost:9092
        key.serializer=org.apache.kafka.common.serialization.StringSerializer
        value.serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
    topics:
      sensors-events: telemetry.sensors.v1
      hubs-events: telemetry.hubs.v1