server:
  port: 0

spring:
  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC
        format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9999/cart-db
    username: postgres
    password: postgres

resilience4j.circuitbreaker:
    instances:
      warehouse:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 15s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true